sudo: false
language: php

php:
  - 5.6
  - 7.0

before_script:
  - composer self-update
  - composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-text
